name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      message:
        description: 'Tag message'
        required: false
        type: string
        default: 'Release version'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in format vX.Y.Z (e.g., v1.0.0)"
            exit 1
          fi

      - name: Check if tag exists
        run: |
          if git rev-parse "${{ inputs.version }}" >/dev/null 2>&1; then
            echo "Error: Tag ${{ inputs.version }} already exists"
            exit 1
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          git tag -a "${{ inputs.version }}" -m "${{ inputs.message }} ${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Summary
        run: |
          echo "✅ Tag ${{ inputs.version }} created successfully" >> $GITHUB_STEP_SUMMARY
          echo "🚀 Build and release workflow will start automatically" >> $GITHUB_STEP_SUMMARY